///////////////////////////////////////////////////////////////////////////////////////////////////////
///
// Welcome to your first Cloud Script revision!
//
// Cloud Script runs in the PlayFab cloud and has full access to the PlayFab Game Server API 
// (https://api.playfab.com/Documentation/Server), and it runs in the context of a securely
// authenticated player, so you can use it to implement logic for your game that is safe from
// client-side exploits. 
//
// Cloud Script functions can also make web requests to external HTTP
// endpoints, such as a database or private API for your title, which makes them a flexible
// way to integrate with your existing backend systems.
//
// There are several different options for calling Cloud Script functions:
//
// 1) Your game client calls them directly using the "ExecuteCloudScript" API,
// passing in the function name and arguments in the request and receiving the 
// function return result in the response.
// (https://api.playfab.com/Documentation/Client/method/ExecuteCloudScript)
// 
// 2) You create PlayStream event actions that call them when a particular 
// event occurs, passing in the event and associated player profile data.
// (https://api.playfab.com/playstream/docs)
// 
// 3) For titles using the Photon Add-on (https://playfab.com/marketplace/photon/),
// Photon room events trigger webhooks which call corresponding Cloud Script functions.
// 
// The following examples demonstrate all three options.
//
///////////////////////////////////////////////////////////////////////////////////////////////////////


// This is a Cloud Script function. "args" is set to the value of the "FunctionParameter" 
// parameter of the ExecuteCloudScript API.
// (https://api.playfab.com/Documentation/Client/method/ExecuteCloudScript)
// "context" contains additional information when the Cloud Script function is called from a PlayStream action.
handlers.helloWorld = function (args, context) {
    
    // The pre-defined "currentPlayerId" variable is initialized to the PlayFab ID of the player logged-in on the game client. 
    // Cloud Script handles authenticating the player automatically.
    var message = "Hello " + currentPlayerId + "!";

    // You can use the "log" object to write out debugging statements. It has
    // three functions corresponding to logging level: debug, info, and error. These functions
    // take a message string and an optional object.
    log.info(message);
    var inputValue = null;
    if (args && args.inputValue)
        inputValue = args.inputValue;
    log.debug("helloWorld:", { input: args.inputValue });

    // The value you return from a Cloud Script function is passed back 
    // to the game client in the ExecuteCloudScript API response, along with any log statements
    // and additional diagnostic information, such as any errors returned by API calls or external HTTP
    // requests. They are also included in the optional player_executed_cloudscript PlayStream event 
    // generated by the function execution.
    // (https://api.playfab.com/playstream/docs/PlayStreamEventModels/player/player_executed_cloudscript)
    return { messageValue: message };
};

// This is a simple example of making a PlayFab server API call
handlers.makeAPICall = function (args, context) {
    var request = {
        PlayFabId: currentPlayerId, Statistics: [{
                StatisticName: "Level",
                Value: 2
            }]
    };
    // The pre-defined "server" object has functions corresponding to each PlayFab server API 
    // (https://api.playfab.com/Documentation/Server). It is automatically 
    // authenticated as your title and handles all communication with 
    // the PlayFab API, so you don't have to write extra code to issue HTTP requests. 
    var playerStatResult = server.UpdatePlayerStatistics(request);
};

// This an example of a function that calls a PlayFab Entity API. The function is called using the 
// 'ExecuteEntityCloudScript' API (https://api.playfab.com/documentation/CloudScript/method/ExecuteEntityCloudScript).
handlers.makeEntityAPICall = function (args, context) {

    // The profile of the entity specified in the 'ExecuteEntityCloudScript' request.
    // Defaults to the authenticated entity in the X-EntityToken header.
    var entityProfile = context.currentEntity;

    // The pre-defined 'entity' object has functions corresponding to each PlayFab Entity API,
    // including 'SetObjects' (https://api.playfab.com/documentation/Data/method/SetObjects).
    var apiResult = entity.SetObjects({
        Entity: entityProfile.Entity,
        Objects: [
            {
                ObjectName: "obj1",
                DataObject: {
                    foo: "some server computed value",
                    prop1: args.prop1
                }
            }
        ]
    });

    return {
        profile: entityProfile,
        setResult: apiResult.SetResults[0].SetResult
    };
};

// This is a simple example of making a web request to an external HTTP API.
handlers.makeHTTPRequest = function (args, context) {
    var headers = {
        "X-MyCustomHeader": "Some Value"
    };
    
    var body = {
        input: args,
        userId: currentPlayerId,
        mode: "foobar"
    };

    var url = "http://httpbin.org/status/200";
    var content = JSON.stringify(body);
    var httpMethod = "post";
    var contentType = "application/json";

    // The pre-defined http object makes synchronous HTTP requests
    var response = http.request(url, httpMethod, content, contentType, headers);
    return { responseContent: response };
};

// This is a simple example of a function that is called from a
// PlayStream event action. (https://playfab.com/introducing-playstream/)
handlers.handlePlayStreamEventAndProfile = function (args, context) {
    
    // The event that triggered the action 
    // (https://api.playfab.com/playstream/docs/PlayStreamEventModels)
    var psEvent = context.playStreamEvent;
    
    // The profile data of the player associated with the event
    // (https://api.playfab.com/playstream/docs/PlayStreamProfileModels)
    var profile = context.playerProfile;
    
    // Post data about the event to an external API
    var content = JSON.stringify({ user: profile.PlayerId, event: psEvent.EventName });
    var response = http.request('https://httpbin.org/status/200', 'post', content, 'application/json', null);

    return { externalAPIResponse: response };
};


// Below are some examples of using Cloud Script in slightly more realistic scenarios

// This is a function that the game client would call whenever a player completes
// a level. It updates a setting in the player's data that only game server
// code can write - it is read-only on the client - and it updates a player
// statistic that can be used for leaderboards. 
//
// A funtion like this could be extended to perform validation on the 
// level completion data to detect cheating. It could also do things like 
// award the player items from the game catalog based on their performance.
handlers.completedLevel = function (args, context) {
    var level = args.levelName;
    var monstersKilled = args.monstersKilled;
    
    var updateUserDataResult = server.UpdateUserInternalData({
        PlayFabId: currentPlayerId,
        Data: {
            lastLevelCompleted: level
        }
    });

    log.debug("Set lastLevelCompleted for player " + currentPlayerId + " to " + level);
    var request = {
        PlayFabId: currentPlayerId, Statistics: [{
                StatisticName: "level_monster_kills",
                Value: monstersKilled
            }]
    };
    server.UpdatePlayerStatistics(request);
    log.debug("Updated level_monster_kills stat for player " + currentPlayerId + " to " + monstersKilled);
};


// In addition to the Cloud Script handlers, you can define your own functions and call them from your handlers. 
// This makes it possible to share code between multiple handlers and to improve code organization.
handlers.updatePlayerMove = function (args) {
    var validMove = processPlayerMove(args);
    return { validMove: validMove };
};


// This is a helper function that verifies that the player's move wasn't made
// too quickly following their previous move, according to the rules of the game.
// If the move is valid, then it updates the player's statistics and profile data.
// This function is called from the "UpdatePlayerMove" handler above and also is 
// triggered by the "RoomEventRaised" Photon room event in the Webhook handler
// below. 
//
// For this example, the script defines the cooldown period (playerMoveCooldownInSeconds)
// as 15 seconds. A recommended approach for values like this would be to create them in Title
// Data, so that they can be queries in the script with a call to GetTitleData
// (https://api.playfab.com/Documentation/Server/method/GetTitleData). This would allow you to
// make adjustments to these values over time, without having to edit, test, and roll out an
// updated script.
function processPlayerMove(playerMove) {
    var now = Date.now();
    var playerMoveCooldownInSeconds = 15;

    var playerData = server.GetUserInternalData({
        PlayFabId: currentPlayerId,
        Keys: ["last_move_timestamp"]
    });

    var lastMoveTimestampSetting = playerData.Data["last_move_timestamp"];

    if (lastMoveTimestampSetting) {
        var lastMoveTime = Date.parse(lastMoveTimestampSetting.Value);
        var timeSinceLastMoveInSeconds = (now - lastMoveTime) / 1000;
        log.debug("lastMoveTime: " + lastMoveTime + " now: " + now + " timeSinceLastMoveInSeconds: " + timeSinceLastMoveInSeconds);

        if (timeSinceLastMoveInSeconds < playerMoveCooldownInSeconds) {
            log.error("Invalid move - time since last move: " + timeSinceLastMoveInSeconds + "s less than minimum of " + playerMoveCooldownInSeconds + "s.");
            return false;
        }
    }

    var playerStats = server.GetPlayerStatistics({
        PlayFabId: currentPlayerId
    }).Statistics;
    var movesMade = 0;
    for (var i = 0; i < playerStats.length; i++)
        if (playerStats[i].StatisticName === "")
            movesMade = playerStats[i].Value;
    movesMade += 1;
    var request = {
        PlayFabId: currentPlayerId, Statistics: [{
                StatisticName: "movesMade",
                Value: movesMade
            }]
    };
    server.UpdatePlayerStatistics(request);
    server.UpdateUserInternalData({
        PlayFabId: currentPlayerId,
        Data: {
            last_move_timestamp: new Date(now).toUTCString(),
            last_move: JSON.stringify(playerMove)
        }
    });

    return true;
}

// This is an example of using PlayStream real-time segmentation to trigger
// game logic based on player behavior. (https://playfab.com/introducing-playstream/)
// The function is called when a player_statistic_changed PlayStream event causes a player 
// to enter a segment defined for high skill players. It sets a key value in
// the player's internal data which unlocks some new content for the player.
handlers.unlockHighSkillContent = function (args, context) {
    var playerStatUpdatedEvent = context.playStreamEvent;
    var request = {
        PlayFabId: currentPlayerId,
        Data: {
            "HighSkillContent": "true",
            "XPAtHighSkillUnlock": playerStatUpdatedEvent.StatisticValue.toString()
        }
    };
    var playerInternalData = server.UpdateUserInternalData(request);
    log.info('Unlocked HighSkillContent for ' + context.playerProfile.DisplayName);
    return { profile: context.playerProfile };
};

// Photon Webhooks Integration
//
// The following functions are examples of Photon Cloud Webhook handlers. 
// When you enable the Photon Add-on (https://playfab.com/marketplace/photon/)
// in the Game Manager, your Photon applications are automatically configured
// to authenticate players using their PlayFab accounts and to fire events that 
// trigger your Cloud Script Webhook handlers, if defined. 
// This makes it easier than ever to incorporate multiplayer server logic into your game.


// Triggered automatically when a Photon room is first created
handlers.RoomCreated = function (args) {
    log.debug("Room Created - Game: " + args.GameId + " MaxPlayers: " + args.CreateOptions.MaxPlayers);
};

// Triggered automatically when a player joins a Photon room
handlers.RoomJoined = function (args) {
    log.debug("Room Joined - Game: " + args.GameId + " PlayFabId: " + args.UserId);
};

// Triggered automatically when a player leaves a Photon room
handlers.RoomLeft = function (args) {
    log.debug("Room Left - Game: " + args.GameId + " PlayFabId: " + args.UserId);
};

// Triggered automatically when a Photon room closes
// Note: currentPlayerId is undefined in this function
handlers.RoomClosed = function (args) {
    log.debug("Room Closed - Game: " + args.GameId);
};

// Triggered automatically when a Photon room game property is updated.
// Note: currentPlayerId is undefined in this function
handlers.RoomPropertyUpdated = function (args) {
    log.debug("Room Property Updated - Game: " + args.GameId);
};

// Triggered by calling "OpRaiseEvent" on the Photon client. The "args.Data" property is 
// set to the value of the "customEventContent" HashTable parameter, so you can use
// it to pass in arbitrary data.
handlers.RoomEventRaised = function (args) {
    var eventData = args.Data;
    log.debug("Event Raised - Game: " + args.GameId + " Event Type: " + eventData.eventType);

    switch (eventData.eventType) {
        case "playerMove":
            processPlayerMove(eventData);
            break;

        default:
            break;
    }
};

// CloudScript: Global Top-5 snapshot without Statistics/Leaderboards
// Stores each player's lifetime playtime in User ReadOnlyData (TotalPlaytime)
// and maintains a shared Top-5 snapshot in a Shared Group (LB_GLOBAL).
//
// Notes:
// - Any player can keep incrementing their own lifetime total.
// - The Top-5 snapshot is best-effort only because Shared Group Data is not
//   designed for large-scale, high-concurrency leaderboard use.

var GROUP_ID = "LB_GLOBAL";
var TOP5_KEY = "Top5";
var TOTAL_KEY = "TotalPlaytime";
var NAME_KEY = "DisplayName";

var _groupEnsured = false;

function ensureGroup() {
    if (_groupEnsured) return;
    try {
        server.CreateSharedGroup({ SharedGroupId: GROUP_ID });
    } catch (e) {
        // Group may already exist; ignore.
    }
    _groupEnsured = true;
}

function isArray(value) {
    return Object.prototype.toString.call(value) === "[object Array]";
}

function toInt(value, fallback) {
    var n = parseInt(value, 10);
    return isNaN(n) ? (fallback || 0) : n;
}

function cleanDisplayName(name, fallback) {
    var result = (typeof name === "string") ? name.trim() : "";
    if (!result) result = fallback || "";
    if (result.length > 32) result = result.substring(0, 32);
    return result;
}

function normalizeTop5(rawTop5) {
    var cleaned = [];
    var seen = {};

    if (!isArray(rawTop5)) return cleaned;

    for (var i = 0; i < rawTop5.length; i++) {
        var e = rawTop5[i];
        if (!e || typeof e.playerId !== "string" || !e.playerId) continue;

        var totalSeconds = Math.max(0, toInt(e.totalSeconds, 0));
        var displayName = cleanDisplayName(e.displayName, "");
        var playerId = e.playerId;

        // If duplicates exist, keep the larger value.
        if (seen[playerId]) {
            if (totalSeconds > seen[playerId].totalSeconds) {
                seen[playerId].totalSeconds = totalSeconds;
                seen[playerId].displayName = displayName || seen[playerId].displayName;
            }
            continue;
        }

        var entry = {
            playerId: playerId,
            displayName: displayName,
            totalSeconds: totalSeconds
        };

        seen[playerId] = entry;
        cleaned.push(entry);
    }

    return cleaned;
}

function sortTop5(top5) {
    top5.sort(function (a, b) {
        if (b.totalSeconds !== a.totalSeconds) return b.totalSeconds - a.totalSeconds;

        var an = (a.displayName || "").toLowerCase();
        var bn = (b.displayName || "").toLowerCase();
        if (an < bn) return -1;
        if (an > bn) return 1;

        if (a.playerId < b.playerId) return -1;
        if (a.playerId > b.playerId) return 1;
        return 0;
    });
}

function readTop5() {
    ensureGroup();

    var res = server.GetSharedGroupData({
        SharedGroupId: GROUP_ID,
        Keys: [TOP5_KEY]
    });

    var top5 = [];
    if (res && res.Data && res.Data[TOP5_KEY] && res.Data[TOP5_KEY].Value) {
        try {
            top5 = JSON.parse(res.Data[TOP5_KEY].Value);
        } catch (e) {
            top5 = [];
        }
    }

    return normalizeTop5(top5);
}

function writeTop5(top5) {
    ensureGroup();

    server.UpdateSharedGroupData({
        SharedGroupId: GROUP_ID,
        Data: {
            Top5: JSON.stringify(top5)
        }
    });
}

function getPlayerLifetime(pid) {
    var ro = server.GetUserReadOnlyData({
        PlayFabId: pid,
        Keys: [TOTAL_KEY, NAME_KEY]
    });

    var oldTotal = 0;
    var savedName = "";

    if (ro && ro.Data) {
        if (ro.Data[TOTAL_KEY] && ro.Data[TOTAL_KEY].Value !== undefined) {
            oldTotal = Math.max(0, toInt(ro.Data[TOTAL_KEY].Value, 0));
        }
        if (ro.Data[NAME_KEY] && ro.Data[NAME_KEY].Value !== undefined) {
            savedName = cleanDisplayName(ro.Data[NAME_KEY].Value, "");
        }
    }

    return {
        totalSeconds: oldTotal,
        displayName: savedName
    };
}

function savePlayerLifetime(pid, totalSeconds, displayName) {
    server.UpdateUserReadOnlyData({
        PlayFabId: pid,
        Data: {
            TotalPlaytime: String(Math.max(0, toInt(totalSeconds, 0))),
            DisplayName: cleanDisplayName(displayName, "")
        }
    });
}

function upsertTop5(top5, pid, displayName, totalSeconds) {
    var found = false;
    for (var i = 0; i < top5.length; i++) {
        if (top5[i].playerId === pid) {
            top5[i].displayName = displayName;
            top5[i].totalSeconds = totalSeconds;
            found = true;
            break;
        }
    }

    if (!found) {
        top5.push({
            playerId: pid,
            displayName: displayName,
            totalSeconds: totalSeconds
        });
    }

    sortTop5(top5);

    if (top5.length > 5) {
        top5 = top5.slice(0, 5);
    }

    return top5;
}

function getRankForPlayer(top5, pid) {
    for (var i = 0; i < top5.length; i++) {
        if (top5[i].playerId === pid) return i + 1;
    }
    return null;
}

handlers.GetTop5 = function (args, ctx) {
    var top5 = readTop5();
    return {
        ok: true,
        top5: top5
    };
};

handlers.IncrementPlaytime = function (args, ctx) {
    var pid = currentPlayerId;
    var delta = Math.max(0, Math.floor((args && args.deltaSeconds) || 0));
    var requestedName = cleanDisplayName(args && args.displayName, "");

    if (!pid) {
        return {
            ok: false,
            error: "No currentPlayerId available."
        };
    }

    // Read the player's current lifetime total.
    var playerState = getPlayerLifetime(pid);
    var oldTotal = playerState.totalSeconds;
    var existingName = playerState.displayName || "";

    var newTotal = oldTotal + delta;

    // Keep the latest non-empty name we have.
    var finalName = requestedName || existingName || pid;

    // Persist the player's lifetime total.
    savePlayerLifetime(pid, newTotal, finalName);

    // Read and update the shared Top-5 snapshot.
    var top5 = readTop5();
    top5 = normalizeTop5(top5);

    var inBoardBefore = false;
    for (var i = 0; i < top5.length; i++) {
        if (top5[i].playerId === pid) {
            inBoardBefore = true;
            break;
        }
    }

    top5 = upsertTop5(top5, pid, finalName, newTotal);

    writeTop5(top5);

    return {
        ok: true,
        playerId: pid,
        addedSeconds: delta,
        oldTotalSeconds: oldTotal,
        newTotalSeconds: newTotal,
        inTop5: getRankForPlayer(top5, pid) !== null,
        rank: getRankForPlayer(top5, pid),
        wasAlreadyInTop5: inBoardBefore,
        top5: top5
    };
};

handlers.banPlayer = function(args){
    var duration = args.duration;
    var reason = args.reason;
    server.BanUsers({Bans:[{DurationInHours:duration,PlayFabId:currentPlayerId,Reason:reason}]});
};

// ------------------------------------------------------------
// Discord notifier for PlayFab CloudScript
// Normal webhook = gameplay notifications
// Error webhook  = failures / exceptions / bad responses
// ------------------------------------------------------------

var DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1486775170491486390/RX59omvXWoFRGQWXY_QAV5crjwJWRyeWWskixh9GJq0LNlEd4kbKddmxvmnS0gPjM-qw";
var DISCORD_ERROR_WEBHOOK_URL = "https://discord.com/api/webhooks/1486775170491486390/RX59omvXWoFRGQWXY_QAV5crjwJWRyeWWskixh9GJq0LNlEd4kbKddmxvmnS0gPjM-qw";

var _errorReportInProgress = false;

function _safe(value, fallback) {
    return (value === null || value === undefined || value === "") ? fallback : value;
}

function _safeJson(value) {
    try {
        return JSON.stringify(value, null, 2);
    } catch (e) {
        return "[unserializable object]";
    }
}

function _formatTimestamp(isoString) {
    try {
        return new Date(isoString).toISOString();
    } catch (e) {
        return new Date().toISOString();
    }
}

function _discordEmbed(options) {
    var embed = {
        title: options.title,
        description: options.description || "",
        color: options.color || 5793266,
        fields: options.fields || [],
        timestamp: options.timestamp || new Date().toISOString()
    };

    if (options.footer) {
        embed.footer = { text: options.footer };
    }

    return { embeds: [embed] };
}

function _postDiscord(webhookUrl, payload) {
    var body = JSON.stringify(payload);

    try {
        var response = http.request(
            webhookUrl,
            "post",
            body,
            "application/json",
            {}
        );

        log.info("Discord webhook response: " + _safeJson(response));
        return response;
    } catch (e) {
        log.error("Discord webhook exception: " + e);
        throw e;
    }
}

function _responseLooksFailed(response) {
    if (response === null || response === undefined) {
        return true;
    }

    // Best-effort checks for varying CloudScript response shapes.
    if (typeof response === "object") {
        if (response.statusCode !== undefined) {
            return response.statusCode < 200 || response.statusCode >= 300;
        }
        if (response.code !== undefined) {
            return response.code < 200 || response.code >= 300;
        }
        if (response.error !== undefined) {
            return true;
        }
    }

    return false;
}

function _reportError(source, errorMessage, details) {
    if (_errorReportInProgress) {
        log.error("Skipping nested error report from: " + source);
        return;
    }

    _errorReportInProgress = true;

    try {
        var payload = _discordEmbed({
            title: "PlayFab CloudScript error",
            description: errorMessage,
            color: 15158332,
            fields: [
                { name: "Source", value: _safe(source, "unknown"), inline: false },
                { name: "Details", value: _safe(details, "No details provided"), inline: false }
            ],
            timestamp: new Date().toISOString(),
            footer: "Automatic error reporting"
        });

        _postDiscord(DISCORD_ERROR_WEBHOOK_URL, payload);
    } catch (reportErr) {
        log.error("Failed to report error to Discord: " + reportErr);
    } finally {
        _errorReportInProgress = false;
    }
}

function _sendToDiscord(payload, contextLabel) {
    try {
        var response = _postDiscord(DISCORD_WEBHOOK_URL, payload);

        if (_responseLooksFailed(response)) {
            _reportError(
                contextLabel || "Discord send",
                "Discord webhook returned a failure response.",
                _safeJson(response)
            );
        }

        return response;
    } catch (e) {
        _reportError(
            contextLabel || "Discord send",
            "Exception while sending to Discord webhook.",
            e.toString()
        );
        return null;
    }
}

function _wrapHandler(handlerName, fn) {
    return function (args, context) {
        try {
            return fn(args || {}, context || {});
        } catch (e) {
            _reportError(
                handlerName,
                "Unhandled exception in handler.",
                e && e.stack ? e.stack : e.toString()
            );
            throw e;
        }
    };
}

// ------------------------------------------------------------
// 1) PlayStream -> Discord for player login / ban
// ------------------------------------------------------------
handlers.NotifyPlayStreamToDiscord = _wrapHandler("NotifyPlayStreamToDiscord", function (args, context) {
    var e = context && context.playStreamEvent ? context.playStreamEvent : {};
    var profile = context && context.playerProfile ? context.playerProfile : {};

    var eventName = _safe(e.EventName, "unknown_event");
    var playerId = _safe(profile.PlayerId || e.EntityId, "unknown_player");
    var displayName = _safe(profile.DisplayName || e.PlatformUserName || e.Username, "Unknown");
    var titleId = _safe(e.TitleId, "unknown_title");

    if (eventName === "player_logged_in") {
        var loginFields = [
            { name: "Player", value: displayName + " (`" + playerId + "`)", inline: false },
            { name: "Platform", value: _safe(e.Platform, "unknown"), inline: true },
            { name: "Time", value: _formatTimestamp(e.Timestamp), inline: true }
        ];

        if (e.Location) {
            var locationText = [
                e.Location.City,
                e.Location.Region,
                e.Location.CountryCode
            ].filter(Boolean).join(", ");

            if (locationText) {
                loginFields.push({ name: "Location", value: locationText, inline: false });
            }
        }

        _sendToDiscord(_discordEmbed({
            title: "Player logged in (MADE BY TANTANTC)",
            description: "A player just authenticated in PlayFab.",
            color: 3066993,
            fields: loginFields,
            timestamp: e.Timestamp
        }), "player_logged_in");

        return { ok: true, routed: "login" };
    }

    if (eventName === "player_banned") {
        var banFields = [
            { name: "Player", value: displayName + " (`" + playerId + "`)", inline: false },
            { name: "Ban ID", value: _safe(e.BanId, "unknown"), inline: true },
            { name: "Permanent", value: _safe(e.PermanentBan, false).toString(), inline: true },
            { name: "Reason", value: _safe(e.BanReason, "No reason provided"), inline: false },
            { name: "Expires", value: e.BanExpiration ? _formatTimestamp(e.BanExpiration) : "Never", inline: false },
            { name: "Title", value: titleId, inline: true }
        ];

        _sendToDiscord(_discordEmbed({
            title: "Player banned (MADE BY TANTANTC)",
            description: "A PlayFab ban was applied.",
            color: 15158332,
            fields: banFields,
            timestamp: e.Timestamp
        }), "player_banned");

        return { ok: true, routed: "ban" };
    }

    return { ok: false, error: "Unsupported PlayStream event: " + eventName };
});

// ------------------------------------------------------------
// 2) Photon room joins -> Discord
// ------------------------------------------------------------
handlers.RoomCreated = _wrapHandler("RoomCreated", function (args, context) {
    var userId = _safe(args.UserId, "unknown_user");
    var username = _safe(args.Username, "unknown");
    var gameId = _safe(args.GameId, "unknown_room");
    var appVersion = _safe(args.AppVersion, "unknown");

    _sendToDiscord(_discordEmbed({
        title: "Photon room created (MADE BY TANTANTC)",
        description: "First player entered a new room.",
        color: 3447003,
        fields: [
            { name: "User", value: username + " (`" + userId + "`)", inline: false },
            { name: "Room", value: gameId, inline: false },
            { name: "App Version", value: appVersion, inline: true },
            { name: "Region", value: _safe(args.Region, "unknown"), inline: true }
        ],
        timestamp: new Date().toISOString()
    }), "RoomCreated");

    return { ResultCode: 0, Message: "Success" };
});

handlers.RoomJoined = _wrapHandler("RoomJoined", function (args, context) {
    var userId = _safe(args.UserId, "unknown_user");
    var username = _safe(args.Username, "unknown");
    var gameId = _safe(args.GameId, "unknown_room");
    var appVersion = _safe(args.AppVersion, "unknown");

    _sendToDiscord(_discordEmbed({
        title: "Photon room joined (MADE BY TANTANTC)",
        description: "A player joined a Photon room.",
        color: 3447003,
        fields: [
            { name: "User", value: username + " (`" + userId + "`)", inline: false },
            { name: "Room", value: gameId, inline: false },
            { name: "App Version", value: appVersion, inline: true },
            { name: "Region", value: _safe(args.Region, "unknown"), inline: true }
        ],
        timestamp: new Date().toISOString()
    }), "RoomJoined");

    return { ResultCode: 0, Message: "Success" };
});

// ------------------------------------------------------------
// 3) Unban notifications
// ------------------------------------------------------------
handlers.NotifyUnbanToDiscord = _wrapHandler("NotifyUnbanToDiscord", function (args, context) {
    var playerId = _safe(args.PlayerId, "unknown_player");
    var displayName = _safe(args.DisplayName, "Unknown");
    var banId = _safe(args.BanId, "unknown");
    var reason = _safe(args.Reason, "No reason provided");

    _sendToDiscord(_discordEmbed({
        title: "Player unbanned (MADE BY TANTANTC)",
        description: "A ban was revoked.",
        color: 3066993,
        fields: [
            { name: "Player", value: displayName + " (`" + playerId + "`)", inline: false },
            { name: "Ban ID", value: banId, inline: true },
            { name: "Reason", value: reason, inline: false }
        ],
        timestamp: new Date().toISOString()
    }), "NotifyUnbanToDiscord");

    return { ok: true };
});

/*
    PlayFab CloudScript: automatic display-name moderation

    What this does:
    - Checks a player's display name automatically
    - Bans for 10 hours if the name matches either list
    - Supports:
        1) profaneWords
        2) sexualWords
    - Detects obfuscation like:
        - random letters/numbers before or after the blocked word
        - punctuation/spaces between characters
        - common leetspeak substitutions like 3 -> e, 1 -> i, 0 -> o, 5 -> s, 7 -> t

    Recommended triggers:
    - player_displayname_changed
    - player_logged_in
    - optional scheduled batch scan for all players in a segment
*/

/* ---------------------------- CONFIGURATION ---------------------------- */

var CONFIG = {
    banHours: 10,

    // If a name matches both lists, sexual takes priority.
    sexualPriority: true,

    // Edit these lists anytime.
    profaneWords: [
        "FUCK",
        "SHIT",
        "PISS",
        "BITCH",
        "ASSHOLE",
        "CUNT",
        "BASTARD",
        "PUSSY",
        "NIGGER",
        "NIGGA",
        "ASS",
        "DICK",
        "HITLER",
        "ADOLF",
        'NGA',
        "NGER",
        "NGGER",
        "NGGA"
    ],

    sexualWords: [
        "SEX",
        "PORN",
        "NUDE",
        "NAKED",
        "HORNY",
        "BLOWJOB",
        "PENIS",
        "VAGINA"
    ],

    reasons: {
        sexual: "Account action taken for an inappropriate sexual username that violates community standards. (AUTOMATED BAN)",
        profane: "Account action taken for an inappropriate profane username that violates community standards. (AUTOMATED BAN)"
    }
};

/* ----------------------------- UTILITIES ------------------------------ */

function getTargetPlayFabId(args) {
    if (args) {
        if (args.playFabId) return String(args.playFabId).trim();
        if (args.PlayFabId) return String(args.PlayFabId).trim();
        if (args.playerId) return String(args.playerId).trim();
        if (args.PlayerId) return String(args.PlayerId).trim();
    }

    if (typeof currentPlayerId !== "undefined" && currentPlayerId) {
        return currentPlayerId;
    }

    throw new Error("No PlayFabId provided.");
}

function getDisplayNameForPlayer(playFabId) {
    var result = server.GetUserAccountInfo({
        PlayFabId: playFabId
    });

    if (!result || !result.UserInfo || !result.UserInfo.TitleInfo) {
        return null;
    }

    return result.UserInfo.TitleInfo.DisplayName || null;
}

function banPlayer(playFabId, reason) {
    return server.BanUsers({
        Bans: [
            {
                PlayFabId: playFabId,
                DurationInHours: CONFIG.banHours,
                Reason: reason
            }
        ]
    });
}

function isAlreadyBanned(playFabId) {
    var info = server.GetUserAccountInfo({ PlayFabId: playFabId });
    return !!(
        info &&
        info.UserInfo &&
        info.UserInfo.TitleInfo &&
        info.UserInfo.TitleInfo.isBanned
    );
}

/*
    Normalization:
    - lowercase
    - remove punctuation/spaces
    - convert common obfuscation characters to their base letters
*/
function normalizeForMatch(value) {
    if (value === null || value === undefined) return "";

    var text = String(value).toLowerCase();

    var map = {
        "0": "O",
        "1": "I",
        "2": "Z",
        "3": "E",
        "4": "A",
        "5": "S",
        "6": "G",
        "7": "T",
        "8": "B",
        "9": "G",
        "@": "A",
        "$": "S",
        "!": "I"
    };

    var out = "";
    for (var i = 0; i < text.length; i++) {
        var ch = text.charAt(i);

        if (map.hasOwnProperty(ch)) {
            out += map[ch];
            continue;
        }

        // Keep only letters and numbers.
        if ((ch >= "A" && ch <= "Z") || (ch >= "0" && ch <= "9")) {
            out += ch;
        }
    }

    return out;
}

function findFirstMatch(displayName, wordList) {
    var normalizedName = normalizeForMatch(displayName);
    if (!normalizedName) return null;

    for (var i = 0; i < wordList.length; i++) {
        var blocked = normalizeForMatch(wordList[i]);
        if (!blocked) continue;

        // This catches:
        // - prefix/suffix stuffing: xxBADWORD123
        // - punctuation: b.a.d.w.o.r.d
        // - common symbol/number substitutions
        if (normalizedName.indexOf(blocked) !== -1) {
            return wordList[i];
        }
    }

    return null;
}

function classifyDisplayName(displayName) {
    var sexualMatch = findFirstMatch(displayName, CONFIG.sexualWords);
    var profaneMatch = findFirstMatch(displayName, CONFIG.profaneWords);

    var matchedCategory = null;
    var matchedTerm = null;
    var banReason = null;

    if (CONFIG.sexualPriority) {
        if (sexualMatch) {
            matchedCategory = "sexual";
            matchedTerm = sexualMatch;
            banReason = CONFIG.reasons.sexual;
        } else if (profaneMatch) {
            matchedCategory = "profane";
            matchedTerm = profaneMatch;
            banReason = CONFIG.reasons.profane;
        }
    } else {
        if (profaneMatch) {
            matchedCategory = "profane";
            matchedTerm = profaneMatch;
            banReason = CONFIG.reasons.profane;
        } else if (sexualMatch) {
            matchedCategory = "sexual";
            matchedTerm = sexualMatch;
            banReason = CONFIG.reasons.sexual;
        }
    }

    return {
        matchedCategory: matchedCategory,
        matchedTerm: matchedTerm,
        banReason: banReason
    };
}

function moderateOnePlayer(playFabId) {
    if (isAlreadyBanned(playFabId)) {
        return {
            playFabId: playFabId,
            alreadyBanned: true,
            banned: false
        };
    }

    var displayName = getDisplayNameForPlayer(playFabId);
    if (!displayName) {
        return {
            playFabId: playFabId,
            banned: false,
            reason: "No display name found."
        };
    }

    var verdict = classifyDisplayName(displayName);

    if (!verdict.matchedCategory) {
        return {
            playFabId: playFabId,
            displayName: displayName,
            banned: false
        };
    }

    var banResult = banPlayer(playFabId, verdict.banReason);

    return {
        playFabId: playFabId,
        displayName: displayName,
        banned: true,
        matchedCategory: verdict.matchedCategory,
        matchedTerm: verdict.matchedTerm,
        banHours: CONFIG.banHours,
        reason: verdict.banReason,
        banResult: banResult
    };
}

/* ------------------------------ HANDLERS ------------------------------- */

/*
    Use this as the main automatic moderation call.
    It can be hooked to:
    - player_displayname_changed
    - player_logged_in
*/
handlers.CheckDisplayNameAndBan = function (args, context) {
    var playFabId = getTargetPlayFabId(args);
    return moderateOnePlayer(playFabId);
};

/*
    Convenience wrapper for display-name-change events.
*/
handlers.OnDisplayNameChanged = function (args, context) {
    var playFabId = getTargetPlayFabId(args);
    return moderateOnePlayer(playFabId);
};

/*
    Convenience wrapper for login events.
*/
handlers.OnPlayerLoggedIn = function (args, context) {
    var playFabId = getTargetPlayFabId(args);
    return moderateOnePlayer(playFabId);
};

/*
    Batch scan handler for scheduled tasks.

    Pass:
    {
      "players": ["PFID1", "PFID2", "PFID3"]
    }

    This is how you sweep many players at once from a scheduled task
    or from an admin process that feeds in IDs.
*/
handlers.ScanDisplayNamesBatch = function (args, context) {
    var players = (args && args.players) ? args.players : [];
    var results = [];

    for (var i = 0; i < players.length; i++) {
        try {
            results.push(moderateOnePlayer(String(players[i]).trim()));
        } catch (e) {
            results.push({
                playFabId: players[i],
                banned: false,
                error: String(e)
            });
        }
    }

    return {
        scanned: results.length,
        results: results
    };
};

/*
    Optional helper to inspect what the current lists are.
*/
handlers.GetModerationLists = function () {
    return {
        banHours: CONFIG.banHours,
        profaneWords: CONFIG.profaneWords,
        sexualWords: CONFIG.sexualWords
    };
};
